//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsProjectNET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MarkId { get; set; }
        public Nullable<int> SellerId { get; set; }
        public Nullable<int> MarkModelId { get; set; }
        public decimal ListPrice { get; set; }
        public int Year { get; set; }
        public string ExteriorColor { get; set; }
        public string InteriorColor { get; set; }
        public int Doors { get; set; }
        public string Fuel { get; set; }
        public int Passengers { get; set; }
        public string Transmission { get; set; }
        public string Condition { get; set; }
        public string Picture { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool Enabled { get; set; }
        public string Description { get; set; }
    
        public virtual MarkModel MarkModel { get; set; }
        public virtual Mark Mark { get; set; }
        public virtual Seller Seller { get; set; }
    }
}
