//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsProjectNET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsProjectdbEntities : DbContext
    {
        public CarsProjectdbEntities()
            : base("name=CarsProjectdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<MarkModel> MarkModels { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
